version: '3.8'

services:
  mysql-dev-workshop3:
    image: mysql:8.0
    container_name: workshop3
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coderslab
      MYSQL_DATABASE: workshop3
    ports:
      - "3306:3306"
    expose:
      - "3306"